version: '3.9'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: ativo_real_postgis
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ativo_real}
      POSTGRES_USER: ${POSTGRES_USER:-ativo_real}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ativo_real}
    ports:
      - "5433:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
